/** Presentation-safe copies of loading/error contracts. */
export const PRESENTATION_ERROR_CATEGORIES = Object.freeze({
  INVALID_REQUEST: 'INVALID_REQUEST', NETWORK: 'NETWORK', TIMEOUT: 'TIMEOUT', HTTP: 'HTTP', CORS: 'CORS',
  ABORTED: 'ABORTED', INVALID_RESPONSE: 'INVALID_RESPONSE', NO_DATA: 'NO_DATA', CACHE: 'CACHE', UNKNOWN: 'UNKNOWN', INTEGRITY: 'INTEGRITY',
});

export const PRESENTATION_LOADING_STATES = Object.freeze({
  IDLE: 'IDLE', LOADING: 'LOADING', SUCCESS: 'SUCCESS', EMPTY: 'EMPTY', NETWORK_ERROR: 'NETWORK_ERROR',
  HTTP_ERROR: 'HTTP_ERROR', TIMEOUT: 'TIMEOUT', INVALID_DATA: 'INVALID_DATA', ABORTED: 'ABORTED', UNKNOWN_ERROR: 'UNKNOWN_ERROR',
});

const RETRYABLE = new Set([
  PRESENTATION_ERROR_CATEGORIES.NETWORK,
  PRESENTATION_ERROR_CATEGORIES.TIMEOUT,
]);

export function isRetryableCategory(category) {
  return RETRYABLE.has(category);
}
