import { DataEvents } from '../data/HistoricalDataManager.js';
import { CandleIntegrity } from '../data/CandleIntegrity.js';

function toSeconds(value) {
  const ms = Date.parse(value);
  if (!Number.isFinite(ms)) throw new Error('Choose a valid start and end date');
  return Math.floor(ms / 1000);
}
function escapeText(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }

export class DataCenterPage {
  constructor({ dataManager, candleStore, candleCache, appState }) {
    this.dataManager = dataManager; this.candleStore = candleStore; this.candleCache = candleCache; this.appState = appState;
    this._destroyed = false; this._unbind = []; this._download = { status: 'idle', loaded: 0, total: 0, pct: 0, error: null }; this._jobs = []; this._renderToken = 0;
  }
  init() {
    if (this._destroyed) return;
    const listen = (event, handler) => this._unbind.push(this.dataManager.on(event, handler));
    listen(DataEvents.LOADING_STARTED, (payload) => { this._download = { status: 'running', loaded: 0, total: 0, pct: 0, error: null, ...payload }; this._upsertJob('Historical data download', 'running'); this.render(); });
    listen(DataEvents.PROGRESS, ({ loaded = 0, total = 0, pct = 0 } = {}) => { this._download = { ...this._download, status: 'running', loaded, total, pct }; this._upsertJob('Historical data download', 'running', pct); this.render(); });
    listen(DataEvents.READY, ({ candles = [] } = {}) => { this._download = { ...this._download, status: 'complete', loaded: candles.length, total: candles.length, pct: 100, error: null }; this._upsertJob('Historical data download', 'complete', 100); this.render(); });
    listen(DataEvents.READY_DEGRADED, ({ candles = [] } = {}) => { this._download = { ...this._download, status: 'degraded', loaded: candles.length, total: candles.length, pct: 100 }; this._upsertJob('Historical data download', 'degraded', 100); this.render(); });
    listen(DataEvents.ERROR, (error) => { this._download = { ...this._download, status: 'failed', error: error?.message || String(error) }; this._upsertJob('Historical data download', 'failed'); this.render(); });
    const onClick = (event) => { const action = event.target.closest?.('[data-data-action]'); if (!action) return; if (action.dataset.dataAction === 'download') this.startDownload(); if (action.dataset.dataAction === 'clear-current') this.clearCurrentDataset(); if (action.dataset.dataAction === 'validate') this.validateCurrentDataset(); };
    document.addEventListener('click', onClick); this._unbind.push(() => document.removeEventListener('click', onClick)); this.render();
  }
  _upsertJob(name, status, progress = null) { const job = this._jobs.find((item) => item.name === name); if (job) Object.assign(job, { status, ...(progress == null ? {} : { progress }) }); else this._jobs.unshift({ name, status, progress: progress ?? 0 }); this._jobs = this._jobs.slice(0, 12); }
  async startDownload() {
    if (['running', 'starting'].includes(this._download.status)) return;
    const symbol = document.getElementById('data-symbol')?.value?.trim().toUpperCase(); const timeframe = document.getElementById('data-timeframe')?.value; const fromValue = document.getElementById('data-from')?.value; const toValue = document.getElementById('data-to')?.value;
    try { const from = toSeconds(fromValue); const to = toSeconds(toValue); if (!symbol || !timeframe) throw new Error('Symbol and timeframe are required'); if (from >= to) throw new Error('End date must be after start date'); this._download = { status: 'starting', loaded: 0, total: 0, pct: 0, error: null, symbol, timeframe, from, to }; this.render(); await this.dataManager.load({ symbol, timeframe, from, to, strict: true }); }
    catch (error) { this._download = { ...this._download, status: 'failed', error: error?.message || String(error) }; this._upsertJob('Historical data download', 'failed'); this.render(); }
  }
  async clearCurrentDataset() { const symbol = this.candleStore.getSymbol() || document.getElementById('data-symbol')?.value?.trim().toUpperCase(); const timeframe = this.candleStore.getTimeframe() || document.getElementById('data-timeframe')?.value; if (!symbol || !timeframe) return; try { this.candleCache.invalidate(symbol, timeframe); this.candleStore.clear(); this._upsertJob('Clear current dataset', 'complete', 100); this.render(); } catch (error) { this._upsertJob('Clear current dataset', 'failed'); this._download = { ...this._download, error: error?.message || String(error) }; this.render(); } }
  validateCurrentDataset() { const candles = this.candleStore.getAll(); const meta = this.candleStore.getMetadata() || {}; if (!candles.length) this._validation = { status: 'empty', message: 'No dataset is currently loaded.' }; else { const result = CandleIntegrity.process(candles, { timeframeSec: meta.timeframeSec, from: meta.effectiveFrom, to: meta.effectiveTo, policy: 'REPAIR', timestampUnit: 'seconds' }); this._validation = { status: result.metadata.invalidCount === 0 && result.metadata.gaps.length === 0 ? 'valid' : 'issues', metadata: result.metadata }; } this._upsertJob('Dataset validation', 'complete', 100); this.render(); }
  _currentCoverage() { const symbol = this.candleStore.getSymbol() || document.getElementById('data-symbol')?.value?.trim().toUpperCase(); const timeframe = this.candleStore.getTimeframe() || document.getElementById('data-timeframe')?.value; return symbol && timeframe ? this.candleCache.getCoverage(symbol, timeframe, { timeframeSec: this.candleStore.getMetadata()?.timeframeSec }) : []; }
  _dateDefaults() { const end = new Date(Date.now() - new Date().getTimezoneOffset() * 60000); const start = new Date(end.getTime() - 30 * 86400000); return { start: start.toISOString().slice(0, 16), end: end.toISOString().slice(0, 16) }; }
  async _storage() { try { return globalThis.navigator?.storage?.estimate ? await globalThis.navigator.storage.estimate() : null; } catch { return null; } }
  async render() { if (this._destroyed) return; const token = ++this._renderToken; const meta = this.candleStore.getMetadata() || {}; const coverage = this._currentCoverage(); const storage = await this._storage(); if (this._destroyed || token !== this._renderToken) return; const symbol = this.candleStore.getSymbol() || this.appState.symbol || 'SOLUSDT'; const timeframe = this.candleStore.getTimeframe() || this.appState.timeframe || '15m'; const defaults = this._dateDefaults(); this._setPage('dashboard', this._dashboard(meta, coverage, storage)); this._setPage('downloads', this._downloads(symbol, timeframe, defaults)); this._setPage('datasets', this._datasets(meta, coverage)); this._setPage('validation', this._validation(meta)); this._setPage('storage', this._storageMarkup(storage)); this._setPage('experiments', this._coming('Experiments', 'Experiment orchestration will consume the dataset and job contracts created here.')); this._setPage('strategies', this._coming('Strategies', 'Strategy definitions and walk-forward results will live here.')); this._setPage('journal', this._coming('Journal', 'Replay notes and research observations will be added here.')); this._setPage('jobs', this._jobsMarkup()); this._setPage('system', this._systemMarkup()); }
  _setPage(name, html) { const el = document.getElementById(`page-${name}`); if (!el) return; const template = document.createElement('template'); template.innerHTML = html; el.replaceChildren(template.content.cloneNode(true)); }
  _header(eyebrow, title, subtitle) { return `<header class="data-page-header"><span class="data-eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></header>`; }
  _card(label, value) { return `<article class="data-card"><span>${label}</span><strong>${value}</strong></article>`; }
  _dashboard(meta, coverage, storage) { const usage = storage?.usage != null ? `${(storage.usage / 1073741824).toFixed(2)} GB` : 'Unavailable'; return `<div class="data-page">${this._header('WORKSPACE','Overview','A control room for market data, replay state and research jobs.')}<div class="data-card-grid">${this._card('Loaded candles',this.candleStore.getCount().toLocaleString())}${this._card('Current dataset',meta.symbol ? `${escapeText(meta.symbol)} · ${escapeText(meta.timeframe)}` : 'None')}${this._card('Cache intervals',coverage.length)}${this._card('Browser storage',usage)}</div><section class="data-panel"><h2>Quick actions</h2><div class="data-action-grid"><a href="#downloads">Download historical data</a><a href="#datasets">Manage datasets</a><a href="#validation">Validate current data</a><a href="#storage">Inspect storage</a></div></section><section class="data-panel"><h2>Current dataset</h2><dl class="data-detail-grid"><div><dt>Symbol</dt><dd>${escapeText(meta.symbol || 'None')}</dd></div><div><dt>Timeframe</dt><dd>${escapeText(meta.timeframe || 'None')}</dd></div><div><dt>Rows</dt><dd>${this.candleStore.getCount().toLocaleString()}</dd></div><div><dt>Quality</dt><dd>${escapeText(meta.quality || 'Unknown')}</dd></div></dl></section></div>`; }
  _downloads(symbol,timeframe,defaults) { const d=this._download; const error=d.error?`<div class="data-alert" role="alert">${escapeText(d.error)}</div>`:''; const progress=['running','starting'].includes(d.status)?`<div class="download-progress"><div class="progress-track"><span style="width:${Math.max(0,Math.min(100,Number(d.pct)||0))}%"></span></div><div><strong>${Number(d.pct||0).toFixed(0)}%</strong><span>${Number(d.loaded||0).toLocaleString()} / ${Number(d.total||0).toLocaleString()} candles</span></div></div>`:''; return `<div class="data-page">${this._header('DATA / DOWNLOADS','Download Center','Fetch validated historical candles into the shared replay cache.')}${error}<section class="data-panel"><form class="data-form" novalidate><label>Symbol<input id="data-symbol" value="${escapeText(symbol)}" autocomplete="off" spellcheck="false"></label><label>Timeframe<select id="data-timeframe">${['1m','5m','15m','30m','1h','4h','1d'].map(tf=>`<option value="${tf}" ${tf===timeframe?'selected':''}>${tf}</option>`).join('')}</select></label><label>Start<input id="data-from" type="datetime-local" value="${defaults.start}"></label><label>End<input id="data-to" type="datetime-local" value="${defaults.end}"></label><button class="data-primary" type="button" data-data-action="download" ${['running','starting'].includes(d.status)?'disabled':''}>${d.status==='complete'?'Download again':'Start download'}</button></form>${progress}<p class="data-note">Downloads use HistoricalDataManager, including cache reuse, retry and integrity checks.</p></section><section class="data-panel"><h2>Download lifecycle</h2><ol class="data-steps"><li>Normalize the requested candle range.</li><li>Reuse clean cached coverage where possible.</li><li>Fetch missing ranges with retry and integrity checks.</li><li>Publish the validated dataset to Replay.</li></ol></section></div>`; }
  _datasets(meta,coverage) { const rows=coverage.length?coverage.map(iv=>`<tr><td>${new Date(iv.from*1000).toISOString()}</td><td>${new Date(iv.to*1000).toISOString()}</td><td>${escapeText(meta.timeframe||'—')}</td></tr>`).join(''):'<tr><td colspan="3">No cached coverage for the current dataset.</td></tr>'; return `<div class="data-page">${this._header('DATA / DATASETS','Dataset Manager','Inspect the active dataset and the cache coverage that backs it.')}<section class="data-panel"><div class="data-card-grid">${this._card('Symbol',escapeText(meta.symbol||'None'))}${this._card('Timeframe',escapeText(meta.timeframe||'None'))}${this._card('Rows',this.candleStore.getCount().toLocaleString())}${this._card('Quality',escapeText(meta.quality||'Unknown'))}</div></section><section class="data-panel"><div class="data-panel-head"><h2>Cached intervals</h2><button type="button" data-data-action="clear-current">Clear current dataset</button></div><div class="data-table-wrap"><table><thead><tr><th>From</th><th>To</th><th>Timeframe</th></tr></thead><tbody>${rows}</tbody></table></div></section></div>`; }
  _validation(meta) { const v=this._validation; const count=this.candleStore.getCount(); const status=v?.status||(meta.quality==='VALID'?'valid':count?'not-run':'empty'); const label=status==='valid'?'VALID':status==='issues'?'ISSUES FOUND':status==='empty'?'NO DATA':'NOT RUN'; const detail=v?.metadata?`Invalid: ${v.metadata.invalidCount??0} · Gaps: ${v.metadata.gaps?.length??0}`:'Run validation against the active candle store.'; return `<div class="data-page">${this._header('DATA / VALIDATION','Data Quality','Make dataset integrity visible before research consumes it.')}<section class="data-panel validation-card"><div class="validation-status ${status}"><span>${label}</span><strong>${count.toLocaleString()} candles</strong><small>${escapeText(detail)}</small></div><button class="data-primary" type="button" data-data-action="validate">Validate current dataset</button></section></div>`; }
  _storageMarkup(storage) { const usage=storage?.usage,quota=storage?.quota,pct=usage&&quota?usage/quota*100:null; return `<div class="data-page">${this._header('DATA / STORAGE','Storage','Understand how much browser storage is available to the replay cache.')}<div class="data-card-grid">${this._card('Used',usage!=null?`${(usage/1073741824).toFixed(2)} GB`:'Unavailable')}${this._card('Quota',quota!=null?`${(quota/1073741824).toFixed(2)} GB`:'Unavailable')}${this._card('Usage',pct!=null?`${pct.toFixed(1)}%`:'Unavailable')}${this._card('Cache',this.candleCache.enableIDB?'IndexedDB enabled':'Memory only')}</div><section class="data-panel"><h2>Storage policy</h2><p>Dataset persistence belongs to CandleCache. This page reports browser capacity rather than pretending the web application controls the operating system filesystem.</p></section></div>`; }
  _jobsMarkup() { const rows=this._jobs.length?this._jobs.map(j=>`<tr><td>${escapeText(j.name)}</td><td><span class="job-status ${j.status}">${escapeText(j.status)}</span></td><td>${j.progress!=null?`${Number(j.progress).toFixed(0)}%`:'—'}</td></tr>`).join(''):'<tr><td colspan="3">No jobs have run in this session.</td></tr>'; return `<div class="data-page">${this._header('SYSTEM / JOBS','Jobs','A lightweight audit trail for data operations started in this browser session.')}<section class="data-panel"><div class="data-table-wrap"><table><thead><tr><th>Job</th><th>Status</th><th>Progress</th></tr></thead><tbody>${rows}</tbody></table></div></section></div>`; }
  _systemMarkup() { return `<div class="data-page">${this._header('SYSTEM','System','Runtime capabilities and data-service health.')}<div class="data-card-grid">${this._card('Replay data service','Ready')}${this._card('IndexedDB',this.candleCache.enableIDB?'Available':'Unavailable')}${this._card('Candle store',`${this.candleStore.getCount().toLocaleString()} rows`)}${this._card('Session','Browser local')}</div><section class="data-panel"><h2>Architecture</h2><p>UI actions flow through HistoricalDataManager, which owns range normalization, cache reuse, fetching, retries and integrity publication.</p></section></div>`; }
  _coming(title,detail) { return `<div class="data-page">${this._header('RESEARCH',title,detail)}<section class="data-panel empty-page"><strong>Workspace reserved</strong><p>The navigation is established now so future research features can attach to the same shell and job contracts.</p></section></div>`; }
  destroy() { if (this._destroyed) return; this._destroyed=true; this._renderToken++; for(const off of this._unbind.splice(0)){try{off?.();}catch{}} }
}
